const Endpoint = {
    BASE_URL : "https://storeaneka.my.id/api",
    CATEGORYIMAGE : "https://storeaneka.my.id/uploads/category/",
    PRODUCTIMAGE : "https://storeaneka.my.id/uploads/product/",
    CUSTOMERIMAGE : "https://storeaneka.my.id/uploads/user/",
    //BASE_URL : "http://127.0.0.1:8000/api",
    //CATEGORYIMAGE : "http://127.0.0.1:8000/uploads/category/",
    //PRODUCTIMAGE : "http://127.0.0.1:8000/uploads/product/",
    //CUSTOMERIMAGE : "http://127.0.0.1:8000/uploads/user/",
    LOGIN : "/login",
    LOGOUT : "/logout",
    CATEGORY : "/category",
    SAVECATEGORY : "/category-save",
    DELETECATEGORY : "/category-delete",
    VIEWCATEGORY : "/category-view",
    VIEWCUSTOMER : "/customer-view",
    UPDATECATEGORY : "/category-update",
    PRODUCT : "/product",
    COUNTPRODUCT: "/product-count",
    SAVEPRODUCT : "/product-save",
    DELETEPRODUCT : "/product-delete",
    VIEWPRODUCT : "/product-view",
    VIEWORDER : "/order-view",
    UPDATEPRODUCT : "/product-update",
    UPDATEORDERSTATUS : "/order-update",
    CUSTOMER : "/customers",
    COUNTCUSTOMER : "/customer-count",
    PAYMENT : "/payments",
    ORDER : "/orders",
    COUNTORDERBYMONTH: "/order-count-by-month",
    COUNTORDERBYYEAR: "/order-count-by-year",
    SUMORDERSBYMONTH: "/orders-sum-by-month",
    SUMORDERSBYYEAR: "/order-sum-by-year",
    CATEGORY : "/category",
    REPORT : "/report"
}

export default Endpoint;